import Head from "next/head";
import NavBar from "@/components/NavBar";
import RecommendationWrapper from "@/components/home/RecommendationWrapper";
import styles from "@/styles/Index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather Recommendations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.pageContainer}>
        <NavBar />
        <RecommendationWrapper />
      </div>
    </>
  );
}